In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("sms.csv")

In [3]:
data.head(5)

  label                                               text
0   ham  Hey RAV!! Are we still meeting @ 6pm today??? ...
1  spam  CONGRATULATIONS!!! You have WON a FREE iPhone ...
2   ham  Rose, can you pls send me the project report b...
3  spam  URGENT!!! Your bank account is suspended!!! Ve...
4   ham  Hey!!! I'm running late today :( Traffic is cr...

In [4]:
import spacy

In [5]:
!python3 -m spacy download en_core_web_lg

Collecting en-core-web-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl (400.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 9.3 MB/s  0:00:400:00:0100:02

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')

In [6]:
nlp = spacy.load("en_core_web_lg")
def dataprocessing(text):
    doc = nlp(text)
    tokens = []
    for token in doc:
        if token.is_stop:
            continue
        if token.is_punct:
            continue
        tokens.append(token.lemma_.lower())
    return " ".join(tokens)
data['text'] = data["text"].apply(dataprocessing)

In [7]:
data.head(5)

  label                                               text
0   ham  hey rav meet 6 pm today bring document laptop ...
1  spam  congratulation win free iphone 15 worth $ 999 ...
2   ham  rose pls send project report 5 pm need review ...
3  spam  urgent bank account suspend verify immediately...
4   ham  hey run late today traffic crazyyyy reach offi...

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data['text'], data['label'], test_size=0.2, random_state=42)

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['label'] = le.fit_transform(data['label'])

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [11]:
vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)

In [12]:
vectorizer.get_feature_names_out()

array(['000', '07045612389', '08098765432', '09012345678', '10', '15',
       '20', '200', '30am', '5000', '80090', '999', 'account', 'act',
       'afternoon', 'alert', 'amazon', 'amazongiftbonus', 'appreciate',
       'area', 'asap', 'assignment', 'atm', 'available', 'avoid',
       'awesome', 'bank', 'block', 'bring', 'bro', 'bug', 'buy', 'cable',
       'card', 'cash', 'catch', 'charger', 'chat', 'check', 'claim',
       'class', 'clean', 'click', 'code', 'coffee', 'com',
       'congratulation', 'consultation', 'crazyyyy', 'customer',
       'dataset', 'datingnow', 'datum', 'deactivate', 'deal', 'dear',
       'detail', 'dial', 'document', 'email', 'evening', 'exclusive',
       'expire', 'fi', 'final', 'forget', 'free', 'freegift', 'gift',
       'github', 'gym', 'hawaii', 'hdmi', 'hear', 'help', 'hey', 'hi',
       'hot', 'http', 'immediately', 'instantly', 'insurance', 'iphone',
       'join', 'know', 'kyc', 'laptop', 'late', 'learning', 'lecture',
       'let', 'limited', 'locked', 'login', 'lottery', 'low', 'machine',
       'maybe', 'meet', 'meeting', 'minute', 'miss', 'mobile', 'model',
       'movie', 'need', 'net', 'new', 'nlp', 'number', 'offer', 'office',
       'pack', 'paypal', 'plan', 'pls', 'pm', 'preprocessing',
       'presentation', 'project', 'push', 'rate', 'rav', 'reach',
       'remember', 'reply', 'report', 'review', 'reward', 'rose', 'run',
       'sale', 'saturday', 'sci', 'secure', 'security', 'select', 'send',
       'session', 'share', 'single', 'slide', 'start', 'step',
       'superdiscount', 'suspend', 'thank', 'ticket', 'today', 'tomorrow',
       'tonight', 'traffic', 'training', 'update', 'urgent', 'usd',
       'vacation', 'verify', 'visit', 'warning', 'weekend', 'win',
       'winner', 'workshop', 'worth', 'www', 'yesterday'], dtype=object)

In [13]:
X_train_vec.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.34074051],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.37641867]])

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc = le.transform(y_test)

In [15]:
X_test_vec = vectorizer.transform(X_test)

In [16]:
from sklearn.svm import LinearSVC

In [17]:
model = LinearSVC()

In [18]:
model.fit(X_train_vec,y_train_enc )

LinearSVC()

In [19]:
y_predict = model.predict(X_test_vec)

In [20]:
y_predict

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1])

In [21]:
X_train_vec

<41x167 sparse matrix of type '<class 'numpy.float64'>'
	with 381 stored elements in Compressed Sparse Row format>

In [22]:
vectorizer.get_feature_names_out()

array(['000', '07045612389', '08098765432', '09012345678', '10', '15',
       '20', '200', '30am', '5000', '80090', '999', 'account', 'act',
       'afternoon', 'alert', 'amazon', 'amazongiftbonus', 'appreciate',
       'area', 'asap', 'assignment', 'atm', 'available', 'avoid',
       'awesome', 'bank', 'block', 'bring', 'bro', 'bug', 'buy', 'cable',
       'card', 'cash', 'catch', 'charger', 'chat', 'check', 'claim',
       'class', 'clean', 'click', 'code', 'coffee', 'com',
       'congratulation', 'consultation', 'crazyyyy', 'customer',
       'dataset', 'datingnow', 'datum', 'deactivate', 'deal', 'dear',
       'detail', 'dial', 'document', 'email', 'evening', 'exclusive',
       'expire', 'fi', 'final', 'forget', 'free', 'freegift', 'gift',
       'github', 'gym', 'hawaii', 'hdmi', 'hear', 'help', 'hey', 'hi',
       'hot', 'http', 'immediately', 'instantly', 'insurance', 'iphone',
       'join', 'know', 'kyc', 'laptop', 'late', 'learning', 'lecture',
       'let', 'limited', 'locked', 'login', 'lottery', 'low', 'machine',
       'maybe', 'meet', 'meeting', 'minute', 'miss', 'mobile', 'model',
       'movie', 'need', 'net', 'new', 'nlp', 'number', 'offer', 'office',
       'pack', 'paypal', 'plan', 'pls', 'pm', 'preprocessing',
       'presentation', 'project', 'push', 'rate', 'rav', 'reach',
       'remember', 'reply', 'report', 'review', 'reward', 'rose', 'run',
       'sale', 'saturday', 'sci', 'secure', 'security', 'select', 'send',
       'session', 'share', 'single', 'slide', 'start', 'step',
       'superdiscount', 'suspend', 'thank', 'ticket', 'today', 'tomorrow',
       'tonight', 'traffic', 'training', 'update', 'urgent', 'usd',
       'vacation', 'verify', 'visit', 'warning', 'weekend', 'win',
       'winner', 'workshop', 'worth', 'www', 'yesterday'], dtype=object)

In [23]:
X_train_vec.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.34074051],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.37641867]])

In [24]:
vectorizer.idf_

array([4.04452244, 3.63905733, 3.63905733, 3.63905733, 3.63905733,
       3.63905733, 3.63905733, 3.63905733, 3.63905733, 4.04452244,
       4.04452244, 3.35137526, 3.35137526, 3.63905733, 3.63905733,
       3.63905733, 3.63905733, 3.63905733, 4.04452244, 4.04452244,
       3.63905733, 4.04452244, 4.04452244, 3.63905733, 4.04452244,
       3.63905733, 3.35137526, 4.04452244, 3.12823171, 3.63905733,
       3.63905733, 3.63905733, 3.63905733, 3.35137526, 4.04452244,
       3.63905733, 3.63905733, 4.04452244, 4.04452244, 3.35137526,
       3.63905733, 3.63905733, 3.35137526, 3.63905733, 3.63905733,
       2.43508453, 3.63905733, 3.63905733, 3.63905733, 4.04452244,
       3.63905733, 4.04452244, 3.35137526, 4.04452244, 3.63905733,
       4.04452244, 3.63905733, 4.04452244, 3.63905733, 4.04452244,
       3.63905733, 3.63905733, 3.63905733, 3.63905733, 3.63905733,
       3.63905733, 2.25276297, 3.63905733, 3.63905733, 3.63905733,
       3.63905733, 3.63905733, 3.63905733, 3.63905733, 4.04452244,
       2.65822808, 4.04452244, 4.04452244, 2.43508453, 2.79175947,
       4.04452244, 3.63905733, 3.63905733, 4.04452244, 3.63905733,
       4.04452244, 3.63905733, 3.63905733, 3.63905733, 3.63905733,
       3.12823171, 3.63905733, 3.63905733, 3.35137526, 4.04452244,
       3.63905733, 3.63905733, 3.63905733, 3.63905733, 3.63905733,
       3.63905733, 3.63905733, 4.04452244, 3.63905733, 3.63905733,
       3.63905733, 3.63905733, 3.63905733, 3.35137526, 4.04452244,
       3.63905733, 3.63905733, 4.04452244, 3.63905733, 3.63905733,
       3.63905733, 2.54044504, 3.63905733, 3.63905733, 3.35137526,
       3.63905733, 3.63905733, 3.12823171, 3.63905733, 3.63905733,
       4.04452244, 3.63905733, 3.12823171, 4.04452244, 2.79175947,
       3.63905733, 3.63905733, 3.63905733, 3.63905733, 3.63905733,
       3.63905733, 3.12823171, 3.12823171, 3.63905733, 3.63905733,
       4.04452244, 3.63905733, 3.35137526, 3.63905733, 3.63905733,
       4.04452244, 4.04452244, 3.63905733, 2.02961942, 3.35137526,
       3.12823171, 3.63905733, 3.63905733, 4.04452244, 4.04452244,
       4.04452244, 3.63905733, 4.04452244, 3.12823171, 3.63905733,
       3.63905733, 3.12823171, 4.04452244, 4.04452244, 3.12823171,
       3.63905733, 3.63905733])